<?php

namespace Brdrgz\DoctorPatientDiagnosisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiagnosisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiagnosisRepository extends EntityRepository
{
}